//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhys.WebContestHost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebContestHostDataModelContainer : DbContext
    {
        public WebContestHostDataModelContainer()
            : base("name=WebContestHostDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    }
}
