//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhys.WebContestHost.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveChecker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActiveChecker()
        {
            this.ProgrammingLanguages = new HashSet<ProgrammingLanguage>();
            this.PerformanceMetrics = new HashSet<PerformanceMetric>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IPAdress { get; set; }
        public System.DateTime LastActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgrammingLanguage> ProgrammingLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceMetric> PerformanceMetrics { get; set; }
    }
}
