
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Exhys.WebContestHost.DataModels
{

using System;
    using System.Collections.Generic;
    
public partial class PerformanceMetric
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public double CPULoad { get; set; }

    public long MaximumMemory { get; set; }

    public long UtilizedMemory { get; set; }



    public virtual ActiveChecker Checker { get; set; }

}

}
