//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhys.WebContestHost.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemStatement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProblemStatement()
        {
            this.Filename = "(None)";
        }
    
        public int Id { get; set; }
        public byte[] Bytes { get; set; }
        public string Filename { get; set; }
    }
}
