//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhys.WebContestHost.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemTest
    {
        public int Id { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }
        public string GroupName { get; set; }
    
        public virtual Problem Problem { get; set; }
    }
}
