
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Exhys.WebContestHost.DataModels
{

using System;
    using System.Collections.Generic;
    
public partial class ProblemSolution
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProblemSolution()
    {

        this.TestStatuses = new HashSet<SolutionTestStatus>();

    }


    public int Id { get; set; }

    public string SourceCode { get; set; }

    public string LanguageAlias { get; set; }

    public byte StatusCode { get; private set; }

    public string Message { get; set; }

    public int ParticipationId { get; set; }



    public virtual Problem Problem { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SolutionTestStatus> TestStatuses { get; set; }

    public virtual Participation Participation { get; set; }

}

}
