//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhys.WebContestHost.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionTestStatus
    {
        public int Id { get; set; }
        public int TestNumber { get; set; }
        public string Input { get; set; }
        public string SolutionOutput { get; set; }
        public string ExpectedOutput { get; set; }
        public string StatusCode { get; set; }
        public double Points { get; set; }
        public bool Feedback_ShowStatus { get; set; }
        public bool Feedback_ShowPoints { get; set; }
        public bool Feedback_ShowInput { get; set; }
        public bool Feedback_ShowOutput { get; set; }
        public bool Feedback_ShowExpectedOutput { get; set; }
    }
}
