//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exhys.WebContestHost.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public System.Guid Id { get; set; }
        public string UserAgentString { get; set; }
        public string BrowserName { get; set; }
        public string IPAdress { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
