

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Exhys.WebContestHost.DataModels
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ExhysContestEntities : DbContext
{
    public ExhysContestEntities()
        : base("name=ExhysContestEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<UserAccount> UserAccounts { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<UserGroup> UserGroups { get; set; }

    public virtual DbSet<Competition> Competitions { get; set; }

    public virtual DbSet<Problem> Problems { get; set; }

    public virtual DbSet<ProblemSolution> ProblemSolutions { get; set; }

    public virtual DbSet<ProblemStatement> ProblemStatements { get; set; }

    public virtual DbSet<ProblemTest> ProblemTests { get; set; }

    public virtual DbSet<ActiveChecker> ActiveCheckers { get; set; }

    public virtual DbSet<ProgrammingLanguage> ProgrammingLanguages { get; set; }

    public virtual DbSet<PerformanceMetric> PerformanceMetrics { get; set; }

    public virtual DbSet<SolutionTestStatus> SolutionTestStatuses { get; set; }

    public virtual DbSet<Participation> Participations { get; set; }

}

}

